// ============================================================================
// ATLAS.OS Task System — Pre-Initialization
// ============================================================================
#include "script_component.hpp"

LOG("Pre-initialization starting...");

// Register module
[
    "tasks",
    createHashMapFromArray [
        ["version", "0.1.0"],
        ["requires", ["main"]],
        ["provides", ["taskManagement", "objectiveTracking"]],
        ["events", [
            "ATLAS_tasks_created",
            "ATLAS_tasks_updated",
            "ATLAS_tasks_completed",
            "ATLAS_tasks_failed"
        ]]
    ]
] call EFUNC(main,registerModule);

// Task registry
GVAR(registry) = createHashMap;

// ---------------------------------------------------------------------------
// CBA Settings — Task System
// ---------------------------------------------------------------------------

// Auto-assign tasks
[
    "ATLAS_tasks_autoAssign",
    "CHECKBOX",
    ["Auto-Assign Tasks", "When enabled, new tasks generated by the OPCOM (capture objectives, defend positions, etc.) are automatically assigned to all players. When disabled, tasks appear in the task list but players must manually select them. Auto-assign is recommended for casual play; manual selection suits milsim where leaders assign tasks."],
    ["ATLAS.OS", "Tasks"],
    true,
    1,
    {}
] call CBA_fnc_addSetting;

// Task notification style
[
    "ATLAS_tasks_notificationStyle",
    "LIST",
    ["Task Notification Style", "How players are notified when tasks are created or updated.\n\nFull: Large notification with sound, map marker flash, and hint text.\n\nMinimal: Small text notification only, no sound.\n\nSilent: No notification — tasks appear silently in the task list."],
    ["ATLAS.OS", "Tasks"],
    [["full", "minimal", "silent"], ["Full (Sound + Visual)", "Minimal (Text Only)", "Silent"], 0],
    1,
    {}
] call CBA_fnc_addSetting;

LOG("Pre-initialization complete.");
