name = "ATLAS.OS"
prefix = "atlas"
mainprefix = "z"

[version]
path = "addons/atlas_main/script_version.hpp"
git_hash = 0

[signing]
authority = "atlas"

[properties]
author = "ATLAS.OS Team"
url = "https://github.com/CySpiegel/ATLAS.OS"
